= Otomatik Ödeme
:hp-tags:

Bakkallar tutmuyorlar artık veresiye defterlerini. Zalimlerin muhasebecilere ihtiyacı kalmıyor. Noterler kapılarına kırmızı iri harflerle "İNDİRİM" yazsa da kimse tenezzül etmiyor devirleri tescil ettirmek için. Darphanede makinelerin homurdanması kesiliyor. Bakır, alüminyum toprağa geri karışıyor. Sözlüklerden çekiliyor kelimeler şapkalarını vestiyerden alarak. 

Sokağa çıkıyorum güllere selam verip hanımeli kokusunu içime çekerek yürüyorum. Arnavut kaldırımına bakıp bu kaldırımın ustası Phillip Hagar Smith olmalı diyorum ona da bir selam gönderip devam ediyorum. Köşe başında dizlerini neredeyse omuzlarıyla aynı hizaya getiren taburelerde oturan birkaç kişiyi görüyorum. Yönümü onlara çevirip yaklaşıyorum. Ne konuştuklarını duyamıyorum henüz ama görüyorum hesap cüzdanlarından -buna defter de denebilir- işlemler akıyor hızla. Hızla gönderiliyor hesaplara kendi hesaplarından. Birinin cüzdanı renk değiştiriyor, bu bir alarm! Bakiyesi bitti ama dert değil alıyor bu sefer az önce gönderdiği hesaptan gönderdiklerine hiç benzemeyenlerden. Kimse tutmuyor hesaplarını, alınanları gönderilenleri. Hepsi otomatik. Konuştuklarını duymak için yaklaşıyorum, duyamadan görüyorum dişlerinin arasına kaçan etleri ölmüş kardeşlerinden. Çantamı yokluyorum, bulduğum kürdanları taburelerin ortasına yerleştirilen kısa bacaklı masaya bırakıp hızla uzaklaşıyorum.

Nereye varacağımı bilmiyorum ama gitmem gerektiği zehabına kapılıyorum. En yakın otobüs durağına doğru yol alıyorum. Durakta bekleyenleri uzaktan görüyorum. Kalabalığı görünce "İyi" diyorum "iyi, daha geçmemiş demek ki." Yüzlerini seçmeden defterlerine takılıyor gözüm daracık durakta sigarasının dumanını salan adama gözüm takılıyor. Dumanın dağılmasına eşlik ediyor defterdeki hareketler. Onun cüzdanı gönderdikçe etrafındakiler alıyor, şaşırıyorum. Şaşkınlığımı durağa yanaşan otobüsün tıslaması bölüyor. Otobüse binip arkadaki boşlukları arıyorum, arka taraflar müsaitmiş şoför öyle dedi, inanıyorum. Gözlerim herkesin taşıdığı cüzdana değiyor hepsinden sekerek en sonunda bir gencin defterine takılıyor. Arap saçına dönen kulaklığını açıyor, tıpaları kulaklarına yerleştirip etrafına seddini örüyor genç adam. Ses dalgaları tünel kazan mahkumlar gibi firar ediyor kulaklıklarından yayılıyor örsleri çekiçleri üzengileri titreterek. Ses artıyor, dalgalar engellerden sekerek kepçelerde toplanıyor. Toplandıkça ses hareketleniyor kulak sahiplerinin defterleri, gelenler var. Kulaklığın sahibi hariç, gidenler var onun defterinden. Ödemeler ritmine uyuyor kabına sığmayan müziğin. Defterler dayanıyor bu hareketliliğe ben dayanamıyorum. İlk durakta terk ediyorum otobüsü. 

Nerede olduğumu anlamak için etrafıma bakınırken gözümü alıyor bir pencereden yayılan ışık. Pencereden içeri bakıyorum. Meşeden bir masa, deri kaplamalı bir koltuk, masanın üzerinde tek bir mum. İki mumun birini yakarken diğerini söndüreni hatırlayıp hayıflanıyorum. Cüzdan şifreli bir kasanın hemen üzerine bırakılmış harareti fark ettiriyor kendini. Havale ediliyor sürekli bir yerlere takip edemiyorum. Şûle arttıkça harareti katlanıyor defterin. Yangın çıkmasından korkup uzaklaşıyorum.    

İnsanlardan kaçıp bir kütüphaneye sığınıyorum. Raflardan kaydırak yapıp bırakıyorum gözlerimi bir kitaptan diğerine. Bir ara  bir kitabın pürüzlü kapağına çarpıp rayından fırlıyor gözlerim. Yakalayamadan pencereye çarpıyor. Kaldırımda gömleğinin sol cebinden hesap cüzdanını çıkaran bir adama sabitleniyor. Cüzdan kararsız kalıyor hangi elde durmalı. Bir sağ elin avucuna düşüyor, bir sol. Saatin sarkacı imreniyor bu salınıma. Eşlik etmek istiyor cüzdana. Çok geçmeden yorgun düşüyor, dağılıyor saatin ibresi. O kadar hızlı yer değiştiriyor ki unutuyorum sağımı solumu, sarımsak mıydı soğan mı? En son hangi elinde karar kılıyor anlayamıyorum. 

Adam hesap cüzdanını açıyor ben raftan çektiğim sözlüğü. Adamın yüzünün nasıl bir hal aldığını göremiyorum. O, gönderileni alınanı incelerken ben terkedilmiş sayfaları hızla ters yüz ediyorum. Adam "Zerre miktarınca unutulmamış!" diye haykırırken gözlerim mıhlanıyor koca sözlükte bir başlarına  nöbete kalan iki kelimeye: Hak ve kul.