= Âşiyan
:hp-tags:

Bir kuş bırakıp gitti kalbimin derinliklerine yumurtasını ilk atışına denk gelirken. Annelik  görevinden -kim bilir belki tam da buydu annelik, büyümesi gereken yerde büyütmek- hızla kaçarken kanatları dolaşmadı birbirine, tüylerinin rengi solmadı ve güzelliğinden ihtişamından eksilen de yoktu. 

İçime bıraktığı bu endişe daha narin aldırdı nefesleri. Kuluçkaya yatan bir kalbin dinginliğiyle yürürken yollarda içerdeki kabuğu çatlatmamanın derdi eşlik ederdi adımlara. Bir gölge gibi ayakları aynı noktadan fışkıran. Ne kadar sürer bu kuluçka, ne vakit başını çıkarır bu yavru? Sâhî çift çift olurdu yumurtaları, demek ki bırakan biliyordu sırrı: _"Olamaz bir hânede mihmân mihmân üstüne"_ Yıllara yayılan bekleyiş, sabrın yoğurulduğu günler ve ümit ağacının sulandığı ikindiler gösterdi görmek isteyenlere. Gözüne hırstan mil çekenlere, sabır taşını havanda dövenlere ve _nefsini yere koyamayanlara_ nasip değil bu temâşâ. Puslu da olsa gören de bendim, görünen de.

Yıllar yılların üstüne katlandı da bir ok fırladı yayından vardı hedefe. Kırılan bir kalp ile çatladı yumurta. Tüyleri daha belli belirsiz gelecekteki güzelliğinden bir eser taşımayan şimdiki çirkin haliyle çıkardı başını çatlaktan. 

O büyüdükçe büyüdü her odası kalbin, hiç darlık çekmedi. Güzelliğine bir işaret olan tüyleri tamamlanmaya görsün açıverdi kanatlarını. Uçacak uçacak da kim eşlik edecek ona? Bir annesi olsaydı beraber süzülürlerdi ruhumun derinliklerine doğru. Bir annesi olsaydı eğer beraber uçarlardı içimde kopan fırtınalara karşı. 

Steteskopundan dinlese bir kulak içerdeki sesleri, üç cemrenin de içimin derinliklerine düştüğünü sanırdı. Baharı kucakladığıma dair zanlar içinde kalırdı. Ve zanların çoğu gibi yanılırdı. İsyanla bağıran bu kuşun cıvıltıları sağ ventrikülün çeperlerinden sekerek sola geçiyor, aorttan vücudun dört köşesine yol bularak parmak uçlarına dek titretiyordu. Hayır, sıtma değildi bu! Deşse de bir neşter göremeyecekler yuvasında bu kuşu çünkü bir sır ve bir emânet.

Bir çare olmalıydı bu kuşu uçuracak. Uçmalıydı artık çünkü hissedemese de kalbin çeperleri zayıf düşüyordu gaga darbelerinden. Bir nefese bindirip salmak mesela gökyüzüne. Ya da bu hikâyedeki gibi her tüyünü bir harf yaparak havalandırmak içimdeki kuşu...