= Başkan'a Arzuhal
:hp-tags:

Bugünlerde 15 yıl olacak Başkan'ım, seni tanıdığımdan senle tanıştığımızdan beri. Yıllar çabuk geçiyor, acelesi var. Okşadığın o şaçlarımda şimdi aklar var Başkan'ım. O kadar çok geçti zaman o kadar fazla eksittik ki bedeni. Yok, hayır asla şikayetçi değilim yanlış anlama beni. Zaman izafi anlatmak zor ne kadar olduğunu. Misal işte benimkiler. 

Hatırlar mısın, nasıl gülümsüyordun yine kalabalıkların arasında? Sana en yakın olanlardan biri bir çocuktu ve o ben. O gün muhtemelen farkında değildim bahtiyarlığın, affet çocuk aklı. Bir çocuğun bile seveceği adamdın sen Başkan'ım. Milletine, vatanına ihanet içinde olanlar sevmedi Başkan'ım seni, sevemezlerdi zaten. Bu sevgi onların kara kalplerini parça parça ederdi. Başkan'ın oy pusulalarında sevmedik biz seni. Seni, _"ben de bu milletin delisiyim!"_ derken suyu üç yudumda içerken her yudumunda ayrı sevdik Başkan'ım. Genç bile demezlerdi daha toydum senle kazanmayı bırak kaybetmeye razıydım.

Geldi çattı mart ayı ve günlerinden yirmi beşi. Elim hadiseyi anons eden tüm dillere lanet okusam mı Başkan'ım? Yine gülümsersin, ben anlarım izin çıkmadı. Yiğit adamdın sen Başkan'ım, soğuksa soğuk senin kemiğin soğukta kaynamıştı. Karanlıksa karanlık, açlıksa açlık. Mamak bugünlere antremanmış Başkan'ım. İşkencelerin ve Filistin askılarının yenemediğini yenemezdi Keş Dağı. Gerçi dağa bıraksan seni bağrına basardı ya işin için de iş olmasaydı. 

Yemin olsun ümit ettim ben. Yakın bir köye ulaşmış bir evin sobası başında ıslanan çoraplarını kurutuyordur dedim Başkan'ım. Sana mihmandar olanların yüzündeki neşeye gıpta bile ettim Başkan'ım. İçin ısınsın diye sıcak bir çorba ikram ettiklerini bile hayal ettim. Gidebilsen ikramda kusur etmezlerdi ona şüphem yok. Ah keşke gidebilsen...

video::227294079[vimeo]