= ???
:hp-tags:

Söze girmek konusunda biraz çekiniyorum. Belki nice benzer cümlelerin kurulduğu, kulaklara abone edildiği bir konuya girmek kolay olmuyor hâliyle. Biraz olsun dışarıdan bakma fırsatını yakaladığım ilk anlardan itibaren bu konu hakkında içimde cümleleri geveleyip durdum. Öyle sanıyorum ki benim için yazmamak yazmaktan evlâ olmayacak. Peşinen varsa hadsizliğim, affımı isteyerek söze girmek niyetindeyim.   

Bir mezuniyet ile öğrencilikte bir merhaleden bir başka merhaleye adım atmış bir kimse olarak hemen ardıma bakıp hicvetmek değil derdim. Bilakis öğrencilik dönemim boyunca kendime getirdiğim eleştirileri bir bakıma bir başka gönüllere emanet etmektir, derdim. Ve bir yönüyle öğrenciliğe devam eden kendim için ise bir hatırlatma, bir ihtar olacaktır. 

Kolay olmayan bir sınav sürecinin ardından üniversiteyi kazanan, üniversiteye kapağı atan(!) daha fikirleri ve tecrübeleri olgunluk düzeyine ulaşmamış resmi geçn gayri-resmi çocuklar 

Şunu bil ki kardeşim: "Her neyse bölümün veya müstakbel mesleğin oranın sana ihtiyacı olmasaydı sana nasip edilmezdi ve bu görev senin omuzlarına bir yerleştirme sonucuyla emanet edilmezdi." Şimdi lütfen bunun farkına var ve görevinin hakkıyla yapmamnın bir yolunu bulma derdine sarıl. İbadet şuurunu seccadenin arasına sıkıştırma, başın dik evinden çık.