= Otomatik Ödeme
:hp-tags:

Bakkallar tutmuyorlar artık veresiye defterlerini. Zalimlerin muhasebecilere ihtiyacı kalmıyor. Noterler kapılarına kırmızı iri harflerle "İNDİRİM" yazsa da kimse tenezzül etmiyor devirleri tescil ettirmek için. Darphanede makinelerin homurdanması kesiliyor. Bakır, alüminyum toprağa geri karışıyor. Sözlüklerden çekiliyor kelimeler şapkalarını vestiyerden alarak. 

Sokağa çıkıyorum güllere selam verip hanımeli kokusunu içime çekerek yürüyorum. Arnavut kaldırımına bakıp bu kaldırımın ustası Phillip Hagar Smith olmalı diyorum ona da bir selam gönderip devam ediyorum. Köşe başında dizlerini neredeyse omuzlarıyla aynı hizaya getiren taburelerde oturan birkaç kişiyi görüyorum. Yönümü onlara çevirip yaklaşıyorum. Ne konuştuklarını duyamıyorum henüz ama görüyorum hesap cüzdanlarından -buna defter de denebilir- işlemler akıyor hızla. Hızla gönderiliyor hesaplara kendi hesaplarından. Birinin cüzdanı renk değiştiriyor, bu bir alarm! Bakiyesi bitti ama dert değil alıyor bu sefer az önce gönderdiği hesaptan gönderdiklerine hiç benzemeyenlerden. Kimse tutmuyor hesaplarını, alınanları gönderilenleri. Hepsi otomatik. Konuştuklarını duymak için yaklaşıyorum, duyamadan görüyorum dişlerinin arasına kaçan etleri ölmüş kardeşlerinden. Çantamı yokluyorum, bulduğum kürdanları taburelerin ortasına yerleştirilen kısa bacaklı masaya bırakıp hızla uzaklaşıyorum.  

*** *
* **  **

Hesap cüzdanını çıkarıyor adam gömleğinin sol cebinden. Cüzdan kararsız kalıyor hangi elde durmalı. Bir sağ elin avucuna düşüyor, bir sol. Saatin sarkacı imreniyor bu salınıma. Eşlik etmek istiyor cüzdana. Çok geçmeden yorgun düşüyor, dağılıyor saatin ibresi. O kadar hızlı yer değiştiriyor ki unutuyorum sağımı solumu, sarımsak mıydı soğan mı? En son hangi elinde karar kılıyor anlayamıyorum. 

Adam hesap cüzdanını açıyor ben raftan çektiğim sözlüğü açıyorum. Adamın yüzünün nasıl bir hal aldığını göremiyorum. O, gönderileni alınanı incelerken ben terkedilmiş sayfaları hızla ters yüz ediyorum. Adam "Zerre miktarınca unutulmamış!" diye haykırırken gözlerim mıhlanıyor bir başlarına  nöbete kalan iki kelimeye: Kul ve hak.