= Kısa Kısa (2)
:hp-tags:

Bir süredir haftada bir yaptığım yolculuklarda farkına vardım ki her yolculuk bana ölümü ciddi anlamda hatırlatıyor. Günlük yaşantıda mezarlık duvarlarının arkasına silkelediğim(iz) bu gerçeği hatırlamama vesile oluyor yolculuklar. Her yolculuk bunu az veya çok bir şekilde yâdıma düşürüyormuş aslında yeni farkettim. Neden sorusu bu sezişin peşine takıldı hemencecik. İlk aklıma gelen cevap şu oldu: "Ölüm de bir yolculuktur neticede. Bu kısa yolculuklar o büyük yolculuğun bir musaggarasıdır." Bir de şöyle tarttım kendimi: "Yoksa geri dönememek korkusu mu bu yaşadığın?", "Ölümü de geri dönüşü olmayan bir gidiş olarak görüyorsun da Dünya'ya düşkünlüğün mü aklına getiriyor onu?" Terazinin iki kefesine iki düşünceyi de bıraktım, tahterevallide oynayan çocuklar gibi hangileri aşağıda hangileri yukarıda göremedim.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Bu yolculukların bitiminde kendimi bir arkadaşın kucağına bırakıverdim. Birkaç aydır uzak kaldığım, avlusunda kedilerin koşturmacasına daldığım Üsküdar Mihrimah Sultan Camiî'nden başka bir yer değildi.  Her seferinde uzaktan gül-endamını seyredip biraz özlem biraz sevinçle yol alıyorum ona doğru. Gece en siyah çarşafı örterken gökyüzüne avlusuna ayak basıyorum, Valide Sultan Camiî ile söyleşmeye başlıyor iki dost. Bölmüyorum onları, dinliyorum bir yandan şadırvandan akan suların sesi. Güneş utangaçlığını kızıllıkların ardında bırakarak gösteriyor kendini. Bir başka dostu görüyorum, uzak kalmanın ırak edemediği bir dostu. Sonra diyorum: "Dostu görmek, bayramdır."

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Yolculuk, okul, iş derken bir yoğunluk kaplıyor dört yanımı. Yapacağım işlerin, görevlerin vs. zihnimi meşgul etmesi sanırım daha yorucu oluyor. Bu yoğunluk içerisinde bir yazıyı okumak için zaman kollamaya çalışıyordum, bir türlü nasip olmuyordu. Okuduğum zaman normalde alamayacağım bir keyfi aldım. Sanırım okumak için gösterdiğim iştiyak kitapla/yazıyla aramda bir bağ oluşmasına vesile oluyor. Aynı durum ruhen, zihnen yoğun olduğum veya kendimi yalnız hissettiğim -yıllardır tek yaşamama rağmen yalnız hissettiğim zamanlar, kalabalıklar içindeki yalnızlığımdan az- anlarda yine ortaya çıkıyor. Romanın bir kahramanı omzuma dokunuyor, bir diğeri elini uzatıyor, öbürü gülümsüyor. Buna en iyi örnek _Nisan'ın 2 Günü_, basit ve yalın bir anlatımı olsa da içinde yer bulduğum bir romandı. Birkaç yıl önce okul kütüphanesinde denk gelip ödünç almıştım. Bir kış günü sırtımı peteğe dayayıp okuduğumu hatırlıyorum. Petek siperin bir cephesi olmuştu, ayaklarımın siperin diğer cephesine değdiğini hissediyordum. Kabzası ayaklarımın ucunda bir tüfek omzuma yaslanmıştı.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

İyi insan tanıyorum, keşke daha önce tanısaydım diyorum. Ve keşkeye öyle bir duygu ve vurgu yüklüyorum ki takat getiremiyor, eziliyor. Bir mahrû -güzel tavrı ay gibi parlıyor- bedâyi-âşinâ (bedâyi-şinas) nasıl olunur öğretiyor. Ben ne kadar öğrenebilirim bilmiyorum. Bir daha *keşke*... 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Cevdet Paşa'nın eli omzuma dokundu.

_Nasıl çıldırmadım hayretdeyim hâlâ sevincimden_ +
_Lisânından seni sevdim sözün gûş itdiğim demler_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Gökte ay, parlıyor; ayın on dördüdür. 

_Sana vardır yüreğimde sözlerim_

video::So6VlDiHukI[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Dede Efendi ne dersin böyle?

video::vvFUnXpoUSE[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

_"Anlatıyorum, hiç konuşmadan,_ +
_Buğdayın içini dökmesi gibi..."_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Bir dua, Kays'ın dilinden gönlüme düşer: +
_"Gittikçe hüsnün eyle ziyâde nigârımın_ +
_Geldikçe derdine beter et müptelâ beni"_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

-_Neden kendi cümlelerinle konuşmazsın?_ +
-Bu hâl, aklımı setr ederken ben nasıl konuşayım? +
-_Peki niye kendine sözcüler bulursun, onların diliyle söylersin?_ +
-Dilim kendi gönlümden konuşsa bu ateş yaş yaprak mı bırakır? +
-_Peki niye susmazsın?_ +
-İçim ile durmadan söyleşirken nasıl susayım? +
-_Haberdar olduğuna delilin var mıdır?_ +
-Bir ay, aydınlığının düştüğü gönülden bigâne midir? +
-_Ne vakte kadar inilersin?_ +
-Vaktin varlığından sıyrılmadan tamam olunur mu? +
-_Neyi beklersin?_ +
-Pervane, şem tutuşmadan ne yapsın? Beklediğim şeminden bir ışıktır.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::asqjpUOo3YE[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Uyutmayan sebep, sen ne güzelsin! 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Ya Karacaoğlan halim ortadadır, hâlâ uyandırmaz mı? +
_"Pervâne şem’ini uyandıramaz_ +
_Başta sevdâ kalpte nâr olmayınca"_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Ümit ve sabır, iki kardeş. Birbirlerine ne güzel sarılıyor şimdi. 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Öyle sermestim ki ne iş ne yolculuk ne okul ne de sınavdan bir yorgunluk hissediyorum. Nasıl sermest olmayayım ki muhatap almışken bu bendeyi? 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Üfleyiverdi yâreme şifa deyu ol mehlikâ +
Amma cûşa getirdi içre ateşi bilmedi

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Acemice, belki hadsizce. Dilime dolanmadan kelimeler söylemek kolay değil. +
Gün doğmasın pencereme ne olur, gecemi aydınlatan ay yeter. +
_Bir nefeslik lafzımda zikrime cânan düşer_

video::244526490[vimeo]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Pervaneyi bir vesvese tutmuş, kaç gecedir  uyumaz beni de uyutmaz. "Söylediklerimle şemi üzer miyim?", diye kara kara düşünür. "Acaba şem pervanenin varlığından hoşnut mudur?" Teselli verdim, ikna etmeye kalkıştım. Kâr etmedi. Ne diyeyim, nasıl edeyim? +
*Pervane kendi acizliğine hatalarına bakıp vesveseye düşerdi. Şem üzülmesin; pervane tevekkül ipine sarıldı, öylece uyudu.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Pervanenin benden başka sırdaşı yok, kime anlatsın halini? Kime döksün içini? Akıtacak gözünden yaşları ama onların sırrını ifşa edeceğinden çekinir. Gözyaşlarını da içinde saklar.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Şem'i üzerlermiş, yorgun bırakırlarmış galiba. Be vefasız Pervane sen de durmaz kendi derdinden söylersin! 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Şeyh Galib'in duasına "Amin!" deriz. 

_"Yâresi muhtâc-ı kâfûr olmasın bir kimsenin_ +
_Sîneden mehpâresi dûr olmasın bir kimsenin"_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::nQh3bOwTnMg[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

En çok yolculuklar düşündürür insana, aklına gelmeyenler yakalar karanlığın ve ıssızlığın ortasında.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Dilimde dua: 
"Hata etmekten koru, usûlsüz vusulden sana sığındık. Cahile yol göster." 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Yazmalı mıyım sâhiden? Sanki yazamadıklarımı da gönlümden okursun. Oku ki kalksın sancısı üzerimden.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Utana sıkıla, incitmekten korkarak...

video::245933662[vimeo]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

-_Kırıyorlar kalbini, yoruyorlar gönlünü nasıl şifa buluyorsun?_ +
-Bir emanet gibi sakladığım cümlelerini okuyup okuyup deva buluyorum.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::QKnuIhKRWu0[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

_"Yüz çevirmem olsa dünya bir yana ben bir yana_ +
_Şem’ine pervâneyim pervâ ne lâzımdır bana_ +
_Anlasın bîgâne bilsin âşinâ sevdim seni"_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Madem andık, bugün de Kâni söylesin: 

_"Mâhum seni ben pençe-i hûrşîde degişmem_ +
_Ol sîne-i sâfî dem-i ispîde degişmem"_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Hadsizliğin zirvesinde yanımda utancım... Bir yıl evvelin sesidir yankılanan ve çirkindir, bilirim. Güzel kılan yegâne şeydir işitecek olan kulaklar. 

"_Sevgili Dost,_ +
_Schumann: "çalarken, seni kimin dinlediğini umursama" diyor. Bense umursuyorum, kimin dinlediğini."_ +

https://vimeo.com/246656385

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Darılma, işte böyle... +
_"Durup dinlenmeden akarsa pınar,_  +
_Her yıl kıştan sonra gelirse bahar,_ +
_Balıkların suyu sevdiği kadar,_  +
_Ben de seni seviyorum, darılma."_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::rxamCTtodME[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Birkaç zorluğun içinde kulaç atarken durdum, farkına vardım. 

_"Sevgili Dost,_ +
_Sen lazımsın bana! Ve önemlisin hadiselerden."_

_"Sevgili Dost,_ +
_Bugün yazmak değil, konuşmak istiyordum seninle. Ama yine yazdım."_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::247592380[vimeo]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

video::FfgLSNglfsY[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Mihrimah'da bulsa vücut.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Nahîfî sormuş: +
_"Göz gördü gönül sevdi seni ey yüzü mâhım_ +
_Kurbânın olam var mı benim bunda günâhım"_ 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

_Mevlam kulu sevdim seni_ 

video::MUZBPnjgzhw[youtube]

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿