= Kısa Kısa
:hp-tags:

Bu yaşıma kadar gerçek anlamda bir mektup yazmak nasip olmamıştı, daha doğrusu ilkokul çağında ödev olarak mektuplar yazılmış ama gönderilmemişti. Bu yaşta nasip oldu, 3 ay kadar önce. 7 yıl evvelin bir kaş çatıklığına olan minnetin vesilesiyle düştü kelimeler kağıda. 

Mektubun ulaştığına dair haberi aldığımda her iki tarafın da gözünden gönlüne akan yaşlar vardı. İşte gökteki yıldızlar. Böylece farkettim yazılacak bir mesajın, e-postanın ve dahi aramanın duyguları taşımaya muvaffak olamadığını. Geçmiyor demek ki duygular, minnet ve şükran filtrelerden. Demek ki taşıyamıyor hava kağıdın taşıdığını.

Bir zaman sonra etrafınızda şöyle güzel insanlar oluyor: Size bir iyiliği veya güzelliği yakıştırdığı için bu iyilik veya güzelliğe sahip olduğunuzda alkışlayan insanlar. Bir yandan şöyle güzel insanları artık çokça göremiyorum etrafımda, bir kötülüğü veya çirkinliği sana yakıştıramadığı için kaş çatan. Üzülüyorum. Keşke olsalar da kötülüğe meylimde çatılsa kaşlar ve ben boyun büksem. 

İşte yıllar evvel çatıldı kaşlar, büküldü boyun. Tam değişecekken yolum, değiştirildi tüm *yoldaş*. Yol güzelleşti, diken battığını farkettim ayaklarıma eski yoldan kalma. Kimi küçük görebilir bu dikenleri ama O bu küçük dikenleri dahi yakıştıramadı bana.

Ve bitti mektup şekillenmesine vesile olunan bir kalpten hürmetlerle...


✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

*Alkışlayan elleri seviyorum, çatılan kaşlara minnettarım.* Alkışlayan eller insanın kibirlenmesi gibi bir tehlikeyi beraberinde getirebiliyor. Çatılan kaşlar ise eşrefî mahlûkāttan bir haber taşıyor. 


✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Uzun zamandır toplu taşıma kullanırken sosyal medya hesaplarına bir göz atamıyorum. Olur da birinin ekrana gözü kayar diye bir endişe taşıyorum. Bu endişe paylaşılan/gönderilen her ne varsa onları bir emanet olarak görmeye başlamamdan kaynaklanıyor. Nerden esti de aklıma düştü bilmiyorum. Hele yanında bir asma kilit salınan hesaplar varsa dikkatim daha da katlanıyor. O küçük asma kilit bana şunları söylüyor: _"İsteseydi tüm dünyaya açardı bu cümleleri ama o bir zümreye bunları emanet ediyor, işte o zümredensin ve göreceklerin/okuyacakların emanet. Sen *emin* misin?"_ Düşündükçe fark ediyor insan, yaşıyoruz işte farkına varmadan kendimizi *emin* addederek. Kim bilir daha nice fark edemeğim boynuma borç olan yükümlülüğüm var. Bilirseniz, bildirin; nasipdar olayım.  

