= **********
:hp-tags: *****

Bir kuş bırakıp gitti kalbimin derinliklerine yumurtasını ilk atışına denk gelirken. Annelik  görevinden -kim bilir belki tam da buydu annelik, büyümesi gereken yerde- hızla kaçarken kanatları dolaşmadı birbirine, tüylerinin rengi solmadı. İçime bıraktığı bu endişe daha narin aldırdı nefesleri. 

Kuluçkaya yatan bir kalbin dinginliğiyle yürürken yollarda içerdeki kabuğu çatlatmamanın derdi eşlik ederdi adımlara. Bir gölge gibi ayakları aynı noktadan fışkıran. Ne kadar sürer bu kuluçka, ne vakit başını çıkarır bu yavru? Sâhî çift çift olurdu yumurtaları, demek ki bırakan biliyordu sırrı: _"Olamaz bir hânede mihmân mihmân üstüne"_ Yıllara yayılan bekleyiş, sabrın yoğurulduğu günler ve ümit ağacının sulandığı ikindiler gösterdi görmek isteyenlere. Gözüne hırstan mil çekenlere nasip değil bu temâşâ. 

Yıllar yılların üstüne katlandı da bir ok fırladı yayından vardı hedefe. Kırılan bir kalp ile çatladı yumurta. Tüyleri daha belli belirsiz gelecekteki güzelliğinden bir eser taşımayan şimdiki çirkin haliyle çıkardı başını çatlaktan. 