= Öykü
:hp-tags:


Muhsin başını yatağından kaldırdığında henüz müezzinlerin saatleri dillerinin bağını çözmemişti. Mahmur gözlerini bir iki defa açıp kapatarak, nefsine baş kaldırmaya çalışıyordu. Onu yastığa esir etmek niyetindeki nefsine...  Böyle alışmıştı Muhsin. Günün bereketi bu zamanda bulunur, diye düşünürdü. Muhsin ayağa kalktı belli belirsiz adımlarla kapıya doğru ilerledi, her sabah yaptığı gibi. Bundan gayrı Muhsin ne yapar söylersek sırrı ifşa ederiz. Aman Allah muhafaza! 

Bileğine kardeşinden hediye saati geçiredursun, bir yandan da beş on dakika ileri almayı adet edindiği duvar saatinden vakti kolluyordu. Dış kapıyı açtı, ayakkabılarını usulca bıraktı. Evden dilinde dua, elinde sürekli yanında taşıdığı sırt çantası ile çıktı. En üst kattan adımlamaya başladı merdivenleri. Oysa apartmanda asansör vardı. Gözü kesmezse, güvenli gelmezse binmezdi Muhsin. Olur da asansör tekler ya içinde kalırsa... Klostrofobisi yoktu, sebebi vardı sanki. Apartmanı terk eder etmez etrafına bakınır, hava istediği gibiyse yüzünde gülümseme belirirdi. Hele bir de kuş cıvıltıları varsa değmeyin keyfine Muhsin'in. O zaman biraz ağır aksak yürürdü servisin alacağı yere doğru. Az biraz daha kuş sesi... 

Servis her zamanki saatinde durakta oluyor, Muhsin de öyle. Arka koltuğa doğru ilerliyor ve köşe tarafına oturuyor. Cep telefonunu ara sıra eline aldığı oluyor, eğer yanına bir başka kimse oturacak olsa hemencecik cebine atıyor. Cep telefonuna düşecek bir resmin veya sözün sahibinden bir emanet, bir sır olarak kendine geldiğini düşünüyor ve üçüncü bir kişinin bunları isteyerek veya istemeyerek görmesine izin vermek istemiyordu. Servis işyerine varıyor ve içini kusuyordu otoparka. Muhsin tasmayı -aslında yaka kartı ama o öyle diyor- boynuna geçiriyor ve turnikeden okutarak işyerine giriş yapıyor. Karton bardak çayı ile birlikte masasına varıyor, etrafındakileri selamladıktan sonra bilgisayarının başına geçiyor. Gün çerisinde yapması gereken işler zihninde bir bir sıraya diziliyor: Gönderilecek e-postalar, toplantı(lar), ...

Gün bitmeden mesai bitiyor. Güneş başını ufka gömmeden kendini servis koltuğunda tekrar buluyor, Muhsin. Gün ne çabuk bitti diye hayıflanıyor bir yandan. Bugün bir de hafta ne çabuk bitti diye düşünüyor, ertelediği iş haricindeki ödevlerini hatırlıyor. Yazmaya niyetlendiği ama bir türlü yazmaya başlayamadığı öyküyü, danışman hocasının istediği raporun ve bilmem nerede sunulacak bildirinin sunumunun hazırlanması gerektiğini hatırlıyor. Servis kalkarken çantasından kitabını çıkarıyor, yazar şehir üzerinden medeniyet tasavvurunu irdeliyor. Muhsin de onunla beraber yaşadığı bir önceki şehirle şimdi yaşadığı şehri kıyaslıyor. Dolduruyor, boşaltıyor zihnini bazen anlamıyor. Şükür ki burada trafik sıkışıklığına pek denk gelinmiyor ve bir an evvel ineceği durağa geliyor. Servisten iniyor, arkasından biri daha.Aldırış etmiyor Muhsin, pek de konuşmak hevesinde değil. Aklında eve vardığında tamamlaması daha doğrusu başlaması gereken işler dönüp duruyor. Ama ne olursa olsun yolunu biraz uzatıp yol kenarında gördüğü hanımellerini koklamayı ihmal etmiyor, yine öyle yapıyor. Ah ne güzel kokuyorlar! Mevsim onları da sıkıştırıyor artık renklerinden vazgeçsinler diye.

Eve varıyor Muhsin, selam veriyor. Evde kimse yok, ama selamın sahibi var. Ah ne güzel sahip! Yedi kat merdivenin yorgunluğunu alnından atmak için yüzüne su çarpıyor. Biraz nefes, iki lokma. Daha sonra yapışıyor yakasına biriktirdiği işler. Pazarlık ediyor sanki onlarla "Söz, haftasonu bakacağım sizlere. Bir müsade edin kalemle dertleşeyim." Masaya geçip yazmaya niyetleniyor. Eline kalemi diline besmeleyi alıp başlıyor yazmaya. Bir mâhruya ithaf edecek, edemiyor, çiziyor üstünü. Kendinden gizlediğini kağıttan esirgemiyor, yazıyor Muhsin: Kuş, kafes, kalp... Başına geleni hikaye ediyor belki de. Kah yazıyor, kah üstünü çiziyor. Tekrar tekrar okuyor, düzeltmeye çalışıyor. Son defa okumak için alıyor eline kağıdı ve başlıyor yüksek sesle okumaya:


_" (I)_ +
_Bir kuş kalbimin derinliklerine yumurtasını bırakıp gitti, ilk atışına denk gelirken. Annelik  görevinden -kim bilir belki tam da buydu annelik, büyümesi gereken yerde büyütmek- hızla kaçarken kanatları dolaşmadı birbirine, tüylerinin rengi solmadı ve güzelliğinden, ihtişamından eksilen de yoktu._

_İçime bıraktığı bu endişe daha narin aldırdı nefesleri. Kuluçkaya yatan bir kalbin dinginliğiyle yürürken yollarda içerdeki kabuğu çatlatmamanın derdi eşlik ederdi adımlara. Bir gölge gibi ayakları aynı noktadan fışkıran. Ne kadar sürer bu kuluçka, ne vakit başını çıkarır bu yavru? Sâhî çift çift olurdu yumurtaları, demek ki bırakan biliyordu sırrı: "Olamaz bir hânede mihmân mihmân üstüne" Yıllara yayılan bekleyiş, sabrın yoğurulduğu günler ve ümit ağacının sulandığı ikindiler gösterdi görmek isteyenlere. Gözüne hırstan mil çekenlere ve sabır taşını havanda dövenlere nasip değil bu temâşâ. Puslu da olsa gören de bendim, görünen de._

_Yıllar yılların üstüne katlandı da bir ok fırladı yayından vardı hedefe. Kırılan bir kalp ile çatladı yumurta. Tüyleri daha belli belirsiz gelecekteki güzelliğinden bir eser taşımayan şimdiki çirkin haliyle çıkardı başını çatlaktan._ 

_O büyüdükçe büyüdü her odası kalbin, hiç darlık çekmedi. Güzelliğine bir işaret olan tüyleri tamamlanmaya görsün açıverdi kanatlarını. Uçacak uçacak da kim eşlik edecek ona? Bir annesi olsaydı beraber süzülürlerdi ruhumun derinliklerine doğru. Bir annesi olsaydı eğer beraber uçarlardı içimde kopan fırtınalara karşı._ 

_Steteskopundan dinlese bir kulak içerdeki sesleri, üç cemrenin de içimin derinliklerine düştüğünü sanırdı. Baharı kucakladığıma dair zanlar içinde kalırdı. Ve zanların çoğu gibi yanılırdı. İsyanla bağıran bu kuşun cıvıltıları sağ ventrikülün çeperlerinden sekerek sola geçiyor, aorttan vücudun dört köşesine yol bularak parmak uçlarına dek titretiyordu. Hayır, sıtma değildi bu! Deşse de bir neşter göremeyecekler yuvasında bu kuşu çünkü bir sır ve bir emânet._

_Bir çare olmalıydı bu kuşu uçuracak. Uçmalıydı artık çünkü hissedemese de kalbin çeperleri zayıf düşüyordu gaga darbelerinden. Bir nefese bindirip salmak mesela gökyüzüne. Ya da bu hikâyedeki gibi her tüyünü bir harf yaparak havalandırmak içimdeki kuşu..._ +

_(II) +
_Hatırlar mısın Âşiyan'ı? Ya da içimde büyüttüğüm yumurtayı, onu bırakan giden kuşu hani? Bu öyle bir kuş ki tüyleri kalem olmuş Şeyh Galib'e, Fuzuli'ye ve daha nicelere. Kim derdini yazacak olsa cömertçe hediye edermiş tüyünü dertlilere._

_Uçururum o kuşu. Bazen içten gelen bir "Ah!" ile bindiririm nefesime ve salarım gökyüzüne. Bazen bir hikayeye harf yaparım onu. Kah bir şiirin mısraları arasında saklanarak çıkar dışarı kah bir notaya sıkı sıkı sarılarak yükselir yüreğimden. Beraber uçacağı annesi yok çünkü. Salınmak zorunda ki zarar etmesin bu yüreğe fakat kimselere belli etmeden, avcılara ve onların etrafında dört dönen tazılarına fark ettirmeden. Ederlerse eğer bir ok çekecek sadaktan  Hüsrev, yayı gerecek. Üzerindeki kanlar kurumadan Ferhat'ın başına vurduğu kazmayı ve kayalardan parça parça ettiği çakıl taşlarını kuşa doğru savuracaklar. Mecnun'a dar gelen çölün kumlarını serpecekler göğe kuşcağızın gözlerine dolsun diye. Nesimi'nin derisindenden yaptıkları köslere indirecekler tokmakları duysun diye cümle ahali. Duysunlar da varsınlar sürek avına._

_Eğer annesi olsaydı yanında, beraber uçacaklardı içimde açan sümbüllerin ve güllerin arasından. Ve onu, kimse ne görecek ne duyacak. Zarif uçuşunu bir annesi bir de ben seyredecektik. Kim bilir belki de annesiyle yekvücud olacaklar._

_Ey Hüma kuşu, bıraktığın bu yumurta senin! Gel ve sahip çık avcılar görmeden köpekler solumadan havayı."_ +

Muhsin okuduktan sonra ardına yaslandı; içini çekti, zihnini yoklayıp Fuzuli'den şu beyiti söyleyip imrendi: +
_"Gezme ey gönlüm kuşu gâfil fezâ-yı ışkda_ + 
_Kim bu sahrânun güzer-gehlerde çok sayyâdı var"_

