= Nihayet
:hp-tags:

Nihayet Dergisi 34. sayısında (Ekim 2017) dosya konusunu "Türk Evi" olarak seçti, bunu duyunca ekim ayının gelmesini dört gözle bekledim. Dergi bu sayısında bir nevi "neyi kaybettiğini hatırla" ihtarıyla okuyucuya ulaşmak istemiş.Dosyayı "Ve Türk, evini kaybeder" başlığıyla açıyor. Mimar Seda Özen'le yapılan söyleşiden altını çizdiğim satırları şöyle sıralayabilirim: +

_"Boğaz'a dik inen sokakları düşünün kimse birbirinin denizini, manzarasını kapatmıyor. ... Komşunun rızası olmayan bir yapıyı inşa edemiyorsunuz. O yıllarda uygulayıp şimdi dikkate almadığımız durum şu anda Avrupa'da uygulanmakta. Yeni yapılacak bir projeyi komşuların onayına sunuyorlar."_ +

Carel Bertram ile yapılan söyleşide _"Müslüman ağırlıklı kültürlerin evleri, mahremiyetleri ile bilinir; diğer bir deyişle, ailenin özel alanını (ev), kurallara veya hatta özel hayat kurallarına uymaya ihtiyaç duymayan insanların yaşadığı kamusal alanla (sokak) ayırırlar."_ ifadelerinin altını çizip düşünüyorum. Şimdi bizler sokakla evlerimizi nasıl ayırıyoruz? Sadece duvarlar yetiyor mu kablolara ekranlara esir olmuşken? +

Kübra Kuruali Yaşar, çocukluğunu geçirdiği İnebolu ve evlerini hatıra olarak bizlere iletiyor. Şu zor sorularla yazısını sonlandırıyor: _"Ya çocuklar! Hareket imkânları kısıtlı evlerde, kaldırımları bile istila eden arabalarla dolu sokaklarda hayal kurmaktan bihaber oyun oynayabiliyorlar mı?Söyleyin bana bir apartmanda doğup büyüseydim çocukluğuma dair bu kadar anı biriktireblir miydim? Neden bizim çocuklarımızın da anlatabileceği hatıraları olmasın?"_ +

Derginin bu sayısında en beğendiğim yazılardan biri Beyza Karakaya tarafından kaleme alınmış, yazıda Osmanlı dönemi ve günümüz ev ilanlarına bakılarak bir evin değerini belirleyen unsurlar göz önüne seriliyor. _"Ev ilanları bize ihtiyacımız olan şeyleri sunmaktan ziyade, sundukları şeyleri önceliklerimiz, ihtiyacımız yapmaya ahdediyor."_ cümlesi daha çok günümüz ilanları için geçerli sanırım. Şu yapılan çıkarım da gayet yerinde: _"O dönemde ev hayatın merkezinde iken bugün ev, hayatın 'merkezine' olan yakınlığı ile ölçülüyor. ... Artık evlerine sığamayan, evlerine sığamadığı için de yaşam merkezini evlerinden AVM'ye, cafelere aktaran bizler önceliklerimizi de bu ölçüde bir hayli değiştirdik."_

İsmail Aydın'ın kendi evini yapma serencamını aktardığı yazı bende de ev yapma isteğini uyandırdı. Belki bir gün, neden olmasın?

Dr. Fairchild Ruggles ile  İslami Bahçeler hakkında bir söyleşi dergide yer alıyor. Dr. Ruggles çiçeğin İslam Bahçeciliği'nde önemi ve anlamını şu cümlelerle anlatıyor: _"Küçük mezarın üzeri süsen, gül ve diğer çiçeklerle minyatür bir bahçe gibidir. Bunu içinde zarif bir ironi vardır: Çiçek kısa ömürlü ve gelip geçicidir ve mevsimsel olarak tekrar yeşerir ve çiçek açar, çünkü yeniden doğuşa ve sonsuluğa işaret eder."_

Türk Evi temasının dışında Endülüs muvaşşahları, gazoz, Şerif Mardin hatıraları, makteller ve Adakale'nin hüzünlü hikayesine de bu sayıda yer verilmiş. Zevk alarak okudum ama kuşe kağıdın kokusu rahatsız etmedi diyemem. 

Ev konusunun bu sıralar dikkatimi çetiği âşikâr, kiralık bir ev arıyorum ve bulmakta zorlanıyorum. Sanırım bu yazılardan sonra kıstaslarım daha da derinleşti, işim artık daha zor.
