= Otomatik Ödeme
:hp-tags:

Bakkallar tutmuyorlar artık veresiye defterlerini. Zalimlerin muhasebecilere ihtiyacı kalmıyor. Noterler kapılarına kırmızı iri harflerle "İNDİRİM" yazsa da kimse tenezzül etmiyor devirleri tescil ettirmek için. Darphanede makinelerin homurdanması kesiliyor. Bakır, aliminyum toprağa geri karışıyor. Sözlüklerden çekiliyor kelimeler şapkalarını vestiyerden alarak. 

Sokağa çıkıyorum kimse 


*** *
* **  **

Hesap cüzdanını çıkarıyor adam gömleğinin sol cebinden. Cüzdan kararsız kalıyor hangi elde durmalı. Bir sağ elin avucuna düşüyor, bir sol. Saatin sarkacı imreniyor bu salınıma. Eşlik etmek istiyor cüzdana. Çok geçmeden yorgun düşüyor, dağılıyor saatin ibresi. O kadar hızlı yer değiştiriyor ki unutuyorum sağımı solumu, sarımsak mıydı soğan mı? En son hangi elinde karar kılıyor anlayamıyorum. 

Adam hesap cüzdanını açıyor ben raftan çektiğim sözlüğü açıyorum. Adamın yüzünün nasıl bir hal aldığını göremiyorum. O, gönderileni alınanı incelerken ben terkedilmiş sayfaları hızla ters yüz ediyorum. Adam "Zerre miktarınca unutulmamış!" diye haykırırken gözlerim mıhlanıyor bir başlarına  nöbete kalan iki kelimeye: Kul ve hak.