= Başkan'a Arzuhal
:hp-tags:

_İçimden dedim*_ tüm cümleleri, sanki karşımdaymış gibi.

Bugünlerde 15 yıl olacak Başkan'ım, seni tanıdığımdan senle tanıştığımızdan beri. Yıllar çabuk geçiyor, acelesi var. Okşadığın o şaçlarımda şimdi aklar var Başkan'ım. O kadar çok geçti zaman o kadar fazla eksittik ki bedeni. Yok, hayır asla şikayetçi değilim yanlış anlama beni. Zaman izafi anlatmak zor ne kadar olduğunu. Misal işte benimkiler. 

Hatırlar mısın, nasıl gülümsüyordun yine kalabalıkların arasında? Sana en yakın olanlardan biri bir çocuktu ve o ben. O gün muhtemelen farkında değildim bahtiyarlığın, affet çocuk aklı. Bir çocuğun bile seveceği adamdın sen Başkan'ım. Milletine, vatanına ihanet içinde olanlar sevmedi Başkan'ım seni, sevemezlerdi zaten. Bu sevgi onların kara kalplerini parça parça ederdi. Başkan'ın oy pusulalarında sevmedik biz seni. Seni, _"ben de bu milletin delisiyim!"_ derken suyu üç yudumda içerken her yudumunda ayrı sevdik Başkan'ım. Genç bile demezlerdi daha toydum senle kazanmayı bırak kaybetmeye razıydım.

Geldi çattı mart ayı ve günlerinden yirmi beşi. Elim hadiseyi anons eden tüm dillere lanet okusam mı Başkam'ım? Yine gülümsersin, ben anlarım izin çıkmadı. Yiğit adamdın sen Başkan'ım, soğuksa soğuk senin kemiğin soğukta kaynamıştı. Karanlıksa karanlık, açlıksa açlık. Mamak bugünlere antremanmış Başkan'ım. İşkencelerin ve Filistin askılarının yenemediğini yenemezdi Keş Dağı. Gerçi dağa bıraksan seni bağrına basardı ya işin için de iş olmasaydı. Kazadan kaza çıkmasaydı.

Yemin olsun ümit ettim ben. Yakın bir köye ulaşmış bir evin sobası başında ıslanan çoraplarını kurutuyordur dedim Başkan'ım. Sana mihmandar olanların yüzündeki neşeye gıpta bile ettim Başkan'ım. İçin ısınsın diye sıcak bir çorba ikram ettiklerini hayal ettim. Gidebilsen ikramda kusur etmezlerdi ona şüphem yok. Ah keşke gidebilsen...


Kaç gün olmuştu da bir haber yoktu senden. Ben okul çıkışı dershane koridorlarında dolaşıyordum, öğretmenler Amerika'dan arama tarama faaliyeti için cihaz geldiğini konuşuyordu kendi aralarında. Ben burun kıvırıyordum, yerini sevmiş olmalıydın ve köyün ahalisi ile gülerek sohbet ediyordun besbelli. 

Ders çıkışında yine duydum konuşanları dillerinde kötü haber. ilk defa başım döndü Başkan'ım. Merdivenlerden inerken trabzanlar koltuk değneğimdi düşmemek için. Bilirsin küçük yerdir bizim memleket, otobüse binmek için yürüdüm. Dörtyolu da bilirsin Başkan'ım, senle tanıştığımız yere çok yakın. İşte orada Başkan'ım üstüme boca etti vitrindeki televizyonlar kırmızı şeritleri, son dakikaları. Ağlamadım, sıktım kendimi. Adımları daha seri attım hıçkıra hıçkıra ağlamadan varmak için durağa. Korktum ağlarsam deli diye yaftalarlar sandım. Keşke hıçkıra hıçkıra ağlasaydım şehrin göbeğinde, deli misin evladım diyenlere senden çaldığım vakarla cevap verseydim: "Evet, bu memleketin delisiyim!"

Eve vardığımda bana kapıyı kim açmıştı hatırlayamadım ama gözlerinde acı haberi teyit etmiştim. Dışarda ağlamaktan korktum, evde hıçkıra hıçkıra ağladım Başkan'ım. Ağlamanın da kazası olurmuş o gün öğrendim. 

Kendime senin şu dizeni vazife bildim:

_"Sevgiyle bakıyor gül gibi görüyorsan sen bahtiyarsın"_

Nasıl gül gibi bakılır hâlâ öğrenemedim, affet.

*Mırıldanmalar-İbrahim Tenekeci

video::4yOWR-Setlg[youtube]