= Titreyen Arş Altında Vals
:hp-tags:

O gün televizyon hiç olmadığı kadar heyecanlıydı. Karıncalı ekranların bile anlatacakları vardı. Bir koşturmaca vardı, tüm sinyaller kovalıyordu birbirini, yetişmeliydi herkesten evvel. İşte elçi müjdeyi vermek için koşuyor krala! Sunucunun ağzından köpükler akıyor, bu nasıl iştah böyle aç kurtları kıskandırıyor. Belli söyleceklerinin ehemmiyeti var. Tüm övgü sözcükleri tükeniyor dilinde. Büyük kâmus şaşkın, gözleri fal taşı. Dil bilimcileri bir telaş kaplıyor, bitmemeliydi burda kelimeler. Hadi karıştırın dil denizini, dalın diplere çıkarın övgü sözcüklerini. Yetmedi, uydurun kelimeler nasıl olsa hepsi övecekler.

Diğer yandan oturdu genç adam koltuğa bir berberde. Damat traşı dedi oysa evliydi. Bir kadın aldı eline bir buket çiçeği. Kim kapacak bu sefer çiçeği, kim kaçacak ki değmesin buket tenine?  Yine cübbe var üstünde memurun, kırmızı kaplı kitabın ona vermiş olduğu yetkiye dayanarak açıyor ağzını. Şahitler de cübbeli, davetiye yok celp neye yetmedi ki? Davetliler hem şaşkın hem mutlu. Çılgınlık sayfası mürekkep çukuru. Eğlenme vaktidir şimdi, ellerini ovuşturuyor İblis. Kârlı alışveriş. Alın çocukları pistten. Elin de tokmak, karar vakti. 

Bin parça şimdi yastık.




*Bilvesile*, birkaç hafta önce denk geldiğim bir haberde şöyle deniliyordu: *"... boşanma düğünü ..."* Sunucunun ağzından köpükler akıyor, işte modern insanın erdiği o yüce şahsiyeti bildiği tüm övgü sözleriyle methediyordu. Aylardır boşanma arefesinde olan çiftlerin hüsranla biten sonlarından haber vermekten kuruyan dudakları, bu haberin verdiği hazla iki yana doğru çekilip büzülüyordu. Haklıydı eşref-i mahlukata yakışmazdı bunca kötü haber. İnsan olmaktan hissedar olamayanların harcıydı ancak yapılanlar, yine haklıydı. Evet onlar haysiyetlerinden ödün vermişlerdi peki bunlar? Doğrusu kavga kıyamet koparmadan çözmekse bu *derdi*, doğru yöntem boşandığı için boşandığı/boşanacağı eşiyle(!) dans etmek miydi? Burada dansın bir kabahati yok, kabahat hiç değilse birlikteliğin sonunda duyulacak ince bir sızının yerini hoyratlığa bırakmasıdır. Ve mırıldanıyor şair, dahi bir ayakkabının ardından +
 +
_Ayağında yenisiyle çıkarken dükkândan_ +
_Kutuya eskisini koyduğun ayakkabılar_ +
_Bir burukluktur ki ayrılmaz ardımızdan_ +
_İnsan neden hep böyle şeyleri hatırlar_

Hatırlamıyor artık kimi insan, başbaşa verse de yıllar boyu.


