= Cahilce Sevmek
:hp-tags: Cahil,  Sevgi, Kara Yosunu,

Bu yazıyı okumak, varsa hatamı düzeltmek için size sorumluluk yükler. Ya el ile, ya dil ile, ya da kalp ile... 

+*************************************************************+

Bilmek ile var olduğumuzu sandığımız günümüz dünyasına varmadan evvel bilmeden var olabilmenin hayat suyuna ağız vermiştik. Başımızdan aşağı boca edilen bilgi yığınlarının bizi biz yaptığına inandırıldığımız günden beri bizden uzak kaldık, biz olamadık. Kalplerimizi akıllarımızla tarttık, aklımıza yatmadıysa burun kıvırdık. Gönlümüzün güzel dediği mantığımıza ters geldi, gönlümüze deryaları sığdırırken aklımız almadı. 

Ne ara, nasıl teslim ettik kendimizi bize teslim edilen aklımıza bilmem ama o gün bu gündür işimiz rast gitmiyor bilirim. Neye el atsak onun bilmişliğine sığınıyor, o bir fiklir beyan etmeden adım atamıyoruz artık. Oysa ne yiğitler tanıdık, *bugünün aklı* yaptıkları karşısında bir set olarak dikilecek. Biz, ne gönül ehlinin menkıbelerine kulak verdik de onlar sırtlarında ciğer satmadan evvel akıllarını satan. Akıl satılmadan satılacak şey değil doğrusu ciğer.

Akılla seviyoruz(!) artık çiçekleri, insanları ve ne görüyorsak ne duyuyorsak. Oysa gözünü dünyaya daha yeni açan bir bebeğin annesini sevmesi gibi olmalıydı. Onu emzirecek, onu büyütecek ve dahi onu yetiştirecek olduğunu bilmeden; sevilmesi gerektiğini bilerek sevmek. Aklın yalnızca sevmenin gerekliliğini bildirdiği zamanlar daha hoş bakıyorduk birbirimize. Ve Yunus sesleniyordu:

_Yaradılanı sev, Yaradan'dan ötürü_

Kim olduğunu bilmeden, gıybete kapı aralamaya imkan dahi vermeyecek az bilgiyle sev diyor Yunus. Bugün gönlümüz yolunu şaşırıp şu öğüdün kapısına varacak olduğunda aklımızı, "sev referans olur", "sev yarın bir gün lazım olur" diyerek kapıda utandırmıyor mu bizi? O kapıya akıl satılmadan varılmıyor, varılsa rezil rüsvâ olmadan dönülmüyor.

Daha aklım beni sevmek konusunda sıkıştırmaya başlamadan evvel yeşil kara yosunlarını severdim. İçinde yaşadığına inandığım küçük insanların nasıl da mutlu olduklarını düşünür sevinirdim. Ayak uçlarında yürür de üstüne basmazdım o küçük insancıkların. Ta ki öğrenene dek kara yosunlarında insancıkların olmadığını. Bildim ama artık sevemedim eskisi gibi. Damla damla su düşüremedim üstlerine susuz kalmasınlar diye. Ve şimdi bu koca şehirde pencere önüne uzaklardan gelen dost edasıyla gelen bir yeşil kara yosunu ve içindeki mutlu insacıklar bu yazıyı yazdırmaya vesile oluyor. Yazarken hatırladım, bugün güneşliydi hava susamış olmalılar. Müsadenizle su vereyim...


