= Titreyen Arş Altında Vals
:hp-tags:

O gün televizyon hiç olmadığı kadar heyecanlıydı. Karıncalı ekranların bile anlatacakları vardı. Bir koşturmaca, tüm sinyaller kovalıyordu birbirini, yetişmeliydi herkesten evvel. İşte elçi müjdeyi vermek için koşuyor krala! Sunucunun ağzından köpükler akıyor, bu nasıl iştah böyle aç kurtları kıskandırıyor. Belli söyleceklerinin ehemmiyeti var. Tüm övgü sözcükleri tükeniyor dilinde. Büyük kâmus şaşkın, gözleri fal taşı. Dil bilimcileri bir telaş kaplıyor, bitmemeliydi burda kelimeler. Hadi karıştırın dil denizini, dalın diplere çıkarın övgü sözcüklerini. Yetmedi, uydurun kelimeler nasıl olsa hepsi övecekler.

Diğer yandan oturdu genç adam koltuğa bir berberde. Damat traşı dedi oysa evliydi. Bir kadın aldı eline bir buket çiçeği. Kim kapacak bu sefer çiçeği, kim kaçacak ki değmesin buket tenine?  Yine cübbe var üstünde memurun, kırmızı kaplı kitabın ona vermiş olduğu yetkiye dayanarak açıyor ağzını. Şahitler de cübbeli, davetiye yok celp neye yetmedi ki? Davetliler hem şaşkın hem mutlu. Çılgınlık sayfası mürekkep çukuru. Eğlenme vaktidir şimdi, ellerini ovuşturuyor İblis. Kârlı alışveriş. Alın çocukları pistten. Elin de tokmak, karar vakti. 

Bin parça şimdi yastık. Hayaller suda, yüzmüyor batıyor. Özkütlesi fazla geldi suya. Kim kazandı, kim kaybetti? İblisin elinde balta, tek vuruşta kesti kurdeleyi. Akan kan da ne, canı yandı kurdelenin. +
 +
-Törenin sonu galiba. +
-Nasıl anladın? +
-İşte fişekler patlıyor! +
-Fişek değil patlayan. +
-Peki nedir? +
-Dökülüyor yıldızlar! +
-Neden? +
-Titriyor arş! +

Hisseden yok titremeyi, tut ellerinden başlasın dans!




