= Duvarlık Dert

:hp-tags: Ahmet, Paşa, dert

Herkesin bir derdi var durur profilinde, evet herkesin derdi 'duvarlarını' süsler(!) oldu. Hepimiz hangimizin derdi daha büyük dercesine yarıştırıyoruz. Kimimizin bitmeyen sınavları, ödevleri derdimizin başrol oyuncusu iken kimimiz bir güzele, bir bıçkına düşen gönlümüzün  vuslata(!) eremeyeşini dert ediyoruz.

Hâl böyle olunca dertsiz olmak, hiç değilse bir sıkıntıya dûçâr olup duvarımıza yapıştıramamak başlı başına bir dert oluyor. "Eh günümüz dünyası" diyecek oluyorum, içimdeki -özüne muhalif- ses eşzamanlı söyleniyor: _"Be utanmaz ya isterse hakkını 'gün' senden birgün!"_ diye. Vazgeçiyorum güne ve şartlara sebep gözüyle bakmaktan.
*Peki neydi derdi olmayınca kusuru kendinde arayanlarla derdinin sebebini başkalarında arayanlar arasındaki o vicdani fark?* Onu ben de bilemiyorum. Öyle ki yine dilime varacak oluyor tüm bilinç kanallarını es geçerek şu kelime: _"Günümüz..."_ Neyse ki yılların tecrübesiyle çıkışıyor içimdeki ses. Varsa bilen, üzerine düşen bilmeyene bildirme görevince söyleyiverirse bu aklı karışığa belki o da yol bulur. 

Bitip tükenmek bilmeyen dertlerinize çare bulmak için okumaya başladıysanız, hakkınız vardır teslim etmek boyun borcudur: +
*"Dün tabîbe derd-i dilden bir devâ sordum dedi +
Gam yemekden özge bu derdin devâsın bilmedim"* +
Ahmet Paşa

Varsa hatam bunu düzeltmek de size vazifedir, düzeltemeyecekseniz doğrulmam için yapmanız gereken son  adım da hâyır duadır :) 
