= Kısa Kısa (2)
:hp-tags:

Bir süredir haftada bir yaptığım yolculuklarda farkına vardım ki her yolculuk bana ölümü ciddi anlamda hatırlatıyor. Günlük yaşantıda mezarlık duvarlarının arkasına silkelediğim(iz) bu gerçeği hatırlamama vesile oluyor yolculuklar. Her yolculuk bunu az veya çok bir şekilde yâdıma düşürüyormuş aslında yeni farkettim. Neden sorusu bu sezişin peşine takıldı hemencecik. İlk aklıma gelen cevap şu oldu: "Ölüm de bir yolculuktur neticede. Bu kısa yolculuklar o büyük yolculuğun bir musaggarasıdır." Bir de şöyle tarttım kendimi: "Yoksa geri dönememek korkusu mu bu yaşadığın?", "Ölümü de geri dönüşü olmayan bir gidiş olarak görüyorsun da Dünya'ya düşkünlüğün mü aklına getiriyor onu?" Terazinin iki kefesine iki düşünceyi de bıraktım, tahterevallide oynayan çocuklar gibi hangileri aşağıda hangileri yukarıda göremedim.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Bu yolculukların bitiminde kendimi bir arkadaşın kucağına bırakıverdim. Birkaç aydır uzak kaldığım, avlusunda kedilerin koşturmacasına daldığım Üsküdar Mihrimah Sultan Camiî'nden başka bir yer değildi.  Her seferinde uzaktan gül-endamını seyredip biraz özlem biraz sevinçle yol alıyorum ona doğru. Gece en siyah çarşafı örterken gökyüzüne avlusuna ayak basıyorum, Valide Sultan Camiî ile söyleşmeye başlıyor iki dost. Bölmüyorum onları, dinliyorum bir yandan şadırvandan akan suların sesi. Güneş utangaçlığını kızıllıkların ardında bırakarak gösteriyor kendini. Bir başka dostu görüyorum, uzak kalmanın ırak edemediği bir dostu. Sonra diyorum: "Dostu görmek, bayramdır."

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Yolculuk, okul, iş derken bir yoğunluk kaplıyor dört yanımı. Yapacağım işlerin, görevlerin vs. zihnimi meşgul etmesi sanırım daha yorucu oluyor. Bu yoğunluk içerisinde bir yazıyı okumak için zaman kollamaya çalışıyordum, bir türlü nasip olmuyordu. Okuduğum zaman normalde alamayacağım bir keyfi aldım. Sanırım okumak için gösterdiğim iştiyak kitapla/yazıyla aramda bir bağ oluşmasına vesile oluyor. Aynı durum ruhen, zihnen yoğun olduğum veya kendimi yalnız hissettiğim -yıllardır tek yaşamama rağmen yalnız hissettiğim zamanlar, kalabalıklar içindeki yalnızlığımdan az- anlarda yine ortaya çıkıyor. Romanın bir kahramanı omzuma dokunuyor, bir diğeri elini uzatıyor, öbürü gülümsüyor. Buna en iyi örnek _Nisan'ın 2 Günü_, basit ve yalın bir anlatımı olsa da içinde yer bulduğum bir romandı. Birkaç yıl önce okul kütüphanesinde denk gelip ödünç almıştım. Bir kış günü sırtımı peteğe dayayıp okuduğumu hatırlıyorum. Petek siperin bir cephesi olmuştu, ayaklarımın siperin diğer cephesine değdiğini hissediyordum. Kabzası ayaklarımın ucunda bir tüfek omzuma yaslanmıştı.

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

İyi insan tanıyorum, keşke daha önce tanısaydım diyorum. Ve keşkeye öyle bir duygu ve vurgu yüklüyorum ki takat getiremiyor, eziliyor. Bir mahrû -güzel tavrı ay gibi parlıyor- bedâyi-âşinâ (bedâyi-şinas) nasıl olunur öğretiyor. Ben ne kadar öğrenebilirim bilmiyorum. Bir daha *keşke*... 

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Cevdet Paşa'nın eli omzuma dokundu.

_Nasıl çıldırmadım hayretdeyim hâlâ sevincimden_ +
_Lisânından seni sevdim sözün gûş itdiğim demler_

✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿✿

Gökte ay, ayın on dördü. 

_Sana vardır yüreğimde sözlerim_

video::So6VlDiHukI[youtube]
